language: node_js
sudo: required
before_cache:
- rm -f ./node_modules/.bin/which
cache:
- directories:
  - node_modules
  - vendor
  - assets/img
script:
- "./_scripts/tests.sh"
branches:
  except:
  - master
node_js:
- '6.1'
before_install:
- rvm install 2.1
- rvm use 2.1
- gem install bundler
- bundle check || bundle install
- npm install
deploy:
  provider: script
  script: "./_scripts/build.sh"
  skip_cleanup: false
  on:
    branch: source
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: E4QTZc7ft66fjWXntRXB/A305AZ2/XSE8YiGURJ+k9x01N5YqnBGfpNDkg6iCjUfucGhDadsumHV5p7UnHGTswk3n7wMsvODSZyuTxWlAgz2Ig4ryJcWgXDDsA9msipWaCdUqUaQ43d5SxrTd1Q/PSTyTXXvVSqS9mKGML2i3idZ2elji6hLvTiG7MTqkGJ1rXCKBAyOMiQPQjDin2wLcpnhcJr7g9lSO8uQbQi4nA2VxKcmGKhSfvxL5iZITxkf4nEnjXNXpl8wys8ay2eWLV9qr2l477FWJOXVxle7rteUA7t/Acw2CEQb5XRRXkwzRRb8rydYsjcnIZw3YfBmDXecwXEW2TlOapkBMXmphu+9nHaYZAKLAE4CswyuyyMpJRExzXrpj1asWtHO6+8t32Az9jfSnDcwYcTq6FIIQc6JwKwnBUdjHrL+brq2SVyqQEsEx5UQNCffejldR+m8R3xc7aG4OR+t6P9N/tjkX+OkIiB/Nw2UXRQz7Pr7UUSIpXkUi9eQRSGv/wG6STP8BfiYNlCc8+dgkiHcOoYeIbYji3DpzhQGfSuuVgnc2O8g11b0Tdi1aq04VrGfPZVuTPHNt3F8+rAJm5BvFI3aV+24m1Dc7p22jrtpr2ckOfzxhqXZQInSaxHUDdJz4yYOjUYPjRLmlW3+Aqef5tNh2G4=
  - secure: KHKI09enSKZEuUFqlS53Z66vFDX+5SqGyV7JO94rXq26lFoyhvdSvbSDpPk42Cz3Q09+77kNBTmRLmkL/LpR1lXQ8mtnaF4aHE/yC8qwsyeu3pUJgUga0PlZFB+uOzbBa0IJHm5wH7BOd4nUZyvGs7wLMCeBFHaNbNHbi3x4G6lqcXZWrlR4gm1AJv0iJaY9nzq2fT48iEGfmtUc8fhVQMLAv9LZWgVg2xp5CasBvYoe68ZdZFHHTitacqbB84vg7WiZKaCJukLcmfomNKa3bQkhqd83OKG49jrbga4U26svrW9ynKAuo3PJ07cd9ljzcbbFvaGS0xBwDnYxcBErY7uHk7W7WWRtfZXlsvjSmp7mfbtvF/CsbE2dHKenv90mVxhpzjI23SQPJCvaren02GVXNpSrm2aCYZLsykD0OIHZDqRDl51Niu24w1+6zkTaG1rYvq3RoDC3400h/OjXTlo4Nl4jL4XpqCD+ZK/9ZXtK5Q3+mHbfND/LGQ6rZvFISXCDeQKaVOoDdgaHAecz9yJoNHJtodaZOzG9dq86kv9Jv07n2xbLtG9XU2C3Zy3Wr37lPJrat59wugnNlYlXOycctsiCuESB4jspAClYfcFxA1omyQM1yjxDwlQUSKJOtmvvlqT+Nv6upeG4Wi1lRt20LxZjJQau+Ci7ivZaK2w=
  - secure: k+co7PqUgRLcY0c82KfCwarT35FnxKn2blmB2QmOm+szOB37dh2S7JeIhR7zX6hTeTabV6xEamkNJTVLk8olaFt1fueNCCONN48asbnDAe/d2Ucll7oyKJVRJCJ+RZn3M4nmfFvWTO6wK/oh/r0/6wdI+dnMFDvX/zdtA3D0xyrm5ddL/K07r8IMB+mDQAR78mnmuMNTDtb5FnXghpp++yFvZbnm6uKYWoRJni2SKMDC/L8nOcEwr8UWJcD9obJzqBwEDoYuzAISl42uxfv35Tux2sAMq/gf7HmU0mOQznepA8vupb8oxbIxWuZy7D2Rl6gW9VQdFKs4EiCGq0z+jZGTBV+xcig+TOgKZbngVkPefFQh0M74w9fPLaaOL1JphF3Fx0dDjlvjlbx+9A4Ymw1QcaNEBy6zMByWaIUxKHlUbQDBaUEAiqQmawOrbjXGs7m3vzZCdrNmvm/VAptqZmQRxboTf3zKnKtIey2GlJpHBtGI75TB8HRXZQciiggFuZKwrIMfj4wHdV+B4UrL3JRxeuKcpBJ6UMyd9GvzdtPIvqsZ01I1jJimQrbd5sViYfxXAfnxMBuDBNicw65JH/VRBvNcRFqWcqOHli4CVB3Zv3AtbBX3Gd1AznZ42BJeyWmh30mETcnu8S+VtxJkcR9GNxTjqvbda+BW259Ze9o=
  - secure: NTiiRFLSBn1G6HK5J+dKOZBby1scS7i0r08xs3nJ0iRq5wm8L7Eso9t8gfZVssOfvKr9UeVSfIXWbdPxw/Hl+jQWeLj5Gk0O9W5F9YV/io7gW1jL4POrH4fESBE2tCe4Akx2xIvscFd9AbkAXIAVAgmDO6VKJa8ZCEMsaSxQNsK0FM99yV9RBC46r7jIzV1EFDyLzk+ybYPvtbrPLWcwLen3UCB/SgNwlepLNaNL16MyKa364WQqlAsghdBsW2iG2T8lUMijc8H+nvlh7Bpq7FvY75XnsMfnJ6dcZQs80RyXa0WySsWsVj3QdKD4q34Q55S9qUr8tOR2vx0GccricLL7/M52bEiyR0AHqSsR+CetGJtpN8eV34sgClio5mt512WCUuMRHkIKk2+aVXODyMozkbS4IEtz2cp88shdA2f7+GB2myO+xtUR4lqbJTZ1Kh0pQZQ9CpovgobZrnrbA5iiAGxrjAUOmSbNSxo9xUvaEQCv0oSi7TmG5o5dOZdwWVBo3IBmsdzrcnZvalpHiQr675qkb/qGJqHAYvpDpVPCX9wN5YzRqbjEW5bw5tSKs3IuxXhCIYZ4TWglD+LdohWJuwj+4Ge/mnaukolQZuNbmD6Tl3SQRB56UGP6arAfN0DuO6HvZsb9nHmeOpFiXLu3Zsp48gFitgyeCa/0CbA=
